product/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
urlpatterns = [
    path('login/',views.login_view, name='login'),
    path('',views.main, name='home'),
    path('register/',views.register, name='register'),
    path('account/',views.account, name = 'account'),
    path('logout/',views.logoutpage, name='logout'),
    path('addrecipe/',views.addyourrecipe, name = 'addrecipe'),
    path('editrecipe/<int:pk>', views.editrecipe, name='editrecipe'),
    path('detail/<int:pk>/',views.detail_view, name ='detail'),
    path('search-recipes',csrf_exempt(views.search_items), name = 'search-recipe'),
]

recipes/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("product.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
import os
from ckeditor.fields import RichTextField

# Create your models here.
def get_file_path(request, filename):
    original_filename = filename
    nowtime = datetime.datetime.now().strftime('%Y%m%d%h,:%M:%S')
    filename = '%s%s' % (nowtime, original_filename)
    return os.path.join('uploads/', filename)


# class Category(models.Model):
#     slug = models.CharField(max_length=150, null=False, blank=False)
#     name = models.CharField(max_length=150, null=False, blank=False)
#     image = models.ImageField(upload_to=get_file_path, null=True, blank=True)
#     description = models.TextField(max_length=300, null=False, blank=False)
#     #this is for degital marketing purpose
#     meta_title = models.CharField(max_length=150, null=False, blank=False)
#     meta_keywords = models.CharField(max_length=150, null=False, blank=False)
#     mate_description = models.TextField(max_length=300, null=False, blank=False)
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.name
class recipe(models.Model):
     user = models.ForeignKey(User, on_delete=models.CASCADE)
     MY_CHOICES = (
        ('veg', 'veg'),
        ('Non_veg', 'Non_veg'),
        
    )
     category = models.CharField(choices=MY_CHOICES, max_length=10, default="Non_veg")
     recipe_name = models.CharField(max_length=150, null=False, blank=False, default='Chiken')
     recipe_image = models.ImageField(upload_to=get_file_path, null=True, blank=True)
     small_description = models.TextField(max_length=250, null=False, blank=False)
     description = models.TextField(max_length=300, null=False, blank=False, default='These crispy Cheddar waffles combine with chicken tenders and a spicy blackberry-muddled maple syrup for a sophisticated version of a classic Southern dish thats also gluten free!')
     prep_time = models.IntegerField(default='15')
     Total_Time = models.IntegerField(default='30')
     Servings = models.IntegerField(default='8', null=False,blank=False)
     Published_at =  models.DateTimeField(auto_now_add=True, blank=False)
     Ingredients = RichTextField(default="some chicken",blank=False, null=False)
     Main_ingredient = models.CharField(max_length=100,default="chiken", null=False, blank=False)
     Directions = RichTextField(blank=False, null=False, default="thsi is directions")
     Cook_note = models.CharField(max_length=400,blank=False, null=False)
     def __str__(self):
            return self.recipe_name
     def get_absolute_url(self):
        return reverse('home')

product/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import recipe
class customuserform(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'username'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'con_password'}))
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
class add_recipe(forms.ModelForm):
    class Meta:
        model = recipe
        fields = '__all__'
# class editrecipe_recipe(forms.ModelForm):
#     class Meta:
#         model = recipe
#         fields = '__all__'
class editrecipe(forms.ModelForm):
    class Meta:
        model = recipe
        fields = ['recipe_name','recipe_image','small_description','description','category','prep_time','Total_Time', 'Servings','Ingredients','Main_ingredient','Directions','Cook_note','user']
        small_description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'class':'form-control'}))
        description = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'class':'form-control'}))
        Directions = forms.CharField(widget=forms.Textarea())
        Ingredients = forms.CharField(widget=forms.Textarea())
        Cook_note = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'class':'form-control'}))
        recipe_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
        prep_time = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}))
        Total_Time = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
        Servings = forms.CharField(widget=forms.NumberInput(attrs={'class':'form-control'}))
        # widgets = {
        #     'recipe_name':forms.TextInput(attrs={'class':'form-control'}),
        #     'small_description':forms.Textarea(attrs={'class':'form-control',"rows":"3"}), 
        #     # 'recipe_image':forms.ImageField(attrs={'class':'form-control'}),
            
        #     # 'body':forms.Textarea(attrs={'class':'form-control'}),
        #     'user':forms.TextInput(attrs={'class':'form-control', 'value':'', 'id':'elder',"type":'hidden'}),
        #    # 'authour':forms.Select(attrs={'class':'form-control'}),
        #     'category':forms.Select(attrs={'class':'form-control'}),
        #     'description':forms.Textarea(attrs={'class':'form-control',"rows":"3"}),
        #     'prep_time':forms.IntegerField(attrs={'class':'form-control'}),
        #     'Total_Time':forms.IntegerField(attrs={'class':'form-control'}),
        #     'Servings':forms.IntegerField(attrs={'class':'form-control'}),
        #     'Main_ingredient':forms.IntegerField(attrs={'class':'form-control'}),
        #     'Directions':forms.Textarea(attrs={'class':'form-control'}),
        #     'Ingredients':forms.Textarea(attrs={'class':'form-control'}),
        #    " Cook_note":forms.Textarea(attrs={'class':'form-control'}),
           
        # }

product/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .forms import customuserform, add_recipe, editrecipe
from .models import recipe
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
import json

def register(request):
    form = customuserform()
    if request.method == 'POST':
        form = customuserform(request.POST)
        if form.is_valid():
            form.save()
            message = 'registered successfully ! login to continue'
            return redirect('/login/')
            messages.success(request, message)
    context = {'form':form}
    return render(request, "product/register.html", context)

def login_view(request):
    if not request.user.is_authenticated:
      if request.method == 'POST':
         lg = AuthenticationForm(request=request, data=request.POST)
         if lg.is_valid():
            uname=lg.cleaned_data['username']
            upass=lg.cleaned_data['password']
            user = authenticate(username=uname, password=upass)
            if user is not None:
               login(request, user)
               messages.success(request, 'logged in successfully')
              
               return HttpResponseRedirect('/')
      else:
        messages.error(request, 'invalid username or password')
        lg = AuthenticationForm()
      return render(request, 'product\login.html',{'form':lg})
    else:
        messages.warning(request, "you are already logged in")
        return HttpResponseRedirect('/')

#logout
def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
        messages.success(request, 'logged out successfully')
    return HttpResponseRedirect('/')
def main(request):
    recipes = recipe.objects.all()
    context = {'recipe':recipes}
    return render(request, 'product/main.html',context)
def account(request):
  
    myrecipe = recipe.objects.filter(user=request.user)
    context = {'myrecipes':myrecipe}
    return render(request, 'product/account.html', context)
login_required('login/')
def addyourrecipe(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = add_recipe(request.POST)
            if form.is_valid():
                form.save()
                return redirect('account/')
        else:
            form = add_recipe()
        context = {'form':form}
        return render(request, 'product/addrecipe.html',context)
    else:
        return HttpResponseRedirect('/login/')
# def edit_post_view(request, pk, slug):
#     Recipe = get_object_or_404(recipe, recipe_name=slug, pk=pk)
#     if request.method == 'POST':
#         form = editrecipe_recipe(request.POST, instance=Recipe)
#         if form.is_valid():
#             form.save()
#             return redirect('acount/', recipe_name=recipe.recipe_name,  id=recipe.pk, )
#     else:
#         form = editrecipe_recipe(instance=pk)
#     return render(request, 'product\editrecipe.html', {'form': form})
# def editrecipe(request, pk):
#     Recipe = recipe.objects.get(id=pk)

#     if request.method == "POST":
#         if len(request.FILES) != 0:
#             if len(Recipe.recipe_image) > 0:
#                 os.remove(Recipe.recipe_name.path)
#             Recipe.recipe_image = request.FILES['recipe_image']

#         Recipe.category = request.POST.get['category']
#         Recipe.recipe_name = request.POST.get['recipe_name']
#         Recipe.small_description = request.POST.get['small_description']
#         Recipe.description = request.POST.get['description']
#         Recipe.prep_time = request.POST.get['prep_time']
#         Recipe.Total_Time = request.POST.get['Total_Time']
#         Recipe.Servings = request.POST.get['Servings']
#         Recipe.Ingredients = request.POST.get['Ingredients']
#         Recipe.Main_ingredient = request.POST.get['Main_ingredient']
#         Recipe.Directions = request.POST.get['Directions']
#         Recipe.Cook_note = request.POST.get['Cook_note']
#         Recipe.save()
#         messages.success(request, 'recipe updated successfully!')
#         redirect('account/')
#     context = {'prod':Recipe}
#     return render(request, 'product\editrecipe.html', context)
# def editrecipe(request, pk):
#     Recipe = get_object_or_404(recipe, pk=pk)
#     if request.method == 'POST':
#         if len(request.FILES) != 0:
#                 if len(Recipe.recipe_image) > 0:
#                     os.remove(Recipe.recipe_name.path)
#                 Recipe.recipe_image = request.FILES['recipe_image']
#         Recipe.category = request.POST.get['category']
#         Recipe.recipe_name = request.POST.get['recipe_name']
#         Recipe.small_description = request.POST.get['small_description']
#         Recipe.description = request.POST.get['description']
#         Recipe.prep_time = request.POST.get['prep_time']
#         Recipe.Total_Time = request.POST.get['Total_Time']
#         Recipe.Servings = request.POST.get['Servings']
#         Recipe.Ingredients = request.POST.get['Ingredients']
#         Recipe.Main_ingredient = request.POST.get['Main_ingredient']
#         Recipe.Directions = request.POST.get['Directions']
#         Recipe.Cook_note = request.POST.get['Cook_note']
       
#         Recipe.save()
#         return redirect('account/')
#     return render(request, 'product/editrecipe.html', {'prod': Recipe})
# def editrecipe(request, pk, instance=None):
#     recipe_id = recipe.objects.get(id=pk)
#     form = editrecipe(instance=recipe_id)
#     context ={'prod':form}
#     return render(request, 'product/editrecipe.html', context)
def editrecipe(request, pk):
    recipes = get_object_or_404(recipe, id=pk)
    if request.method == 'POST':
        # Create a form instance with the POST data and the instance as the initial data
        form = editrecipe(request.POST, instance=recipes)
        # Validate the form
        if form.is_valid():
            # Save the form and redirect to a success page
            form.save()
            return redirect('/')
    else:
        # Create a form instance with the instance as the initial data
        form = editrecipe(instance=recipes)
    # Render the form template with the form instance as context
    return render(request, 'product/editrecipe.html', {'prod': form})
def detail_view(request, pk):
    if(recipe.objects.filter(id=pk)):
          detail_item = recipe.objects.filter(id=pk).first()
          context = {'detail':detail_item}
    else:
        messages.error(request, 'no such category found')
        
        return redirect("/")
    return render(request, 'product/detailview.html', context)
def search_items(request):
    if request.method == "POST":
       
        search_str = json.loads(request.body).get("searchText")
        recipe_items = recipe.objects.filter(
            recipe_name__startswith=search_str, user=request.user) | recipe.objects.filter(
                small_description__startswith=search_str, user=request.user) | recipe.objects.filter(
                    Main_ingredient__icontains=search_str, user=request.user) | recipe.objects.filter(
                        category__icontains=search_str, user=request.user
                    )
        data = recipe_items.values()
        return JsonResponse(list(data), safe=False)
       

product/templates/product/account.html
{% extends 'product\main.html' %}
{% load static %}
{% block main %}
<!--main profile-->
<section class="pt-5" style="background-color: #f1f5f9;">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-xl-12 col-lg-12 col-md-12 col-12">
        <!-- Bg -->
        
        <img src="{% static 'images\profile-bg.jpg' %}" alt="" class="pt-16 rounded-top-md rounded-2" style="background-size: cover; background-repeat: no-repeat;">
        <div class="card rounded-0 rounded-bottom  px-4  pt-2 pb-4 ">
        <div
          class="d-flex align-items-end justify-content-between  ">
          <div class="d-flex align-items-center">
            <div class="me-2 position-relative d-flex justify-content-end align-items-end mt-n5">
              <img src="{% static 'images\istockphoto-1223671392-612x612.jpg' %}" class="avatar-xl rounded-circle border border-4 border-white"
                alt="">
            </div>
            <div class="lh-1">
              <h2 class="mb-0">{{request.user.username}}
               
              </h2>
              <p class=" mb-0 d-block">{{request.user.email}}</p>
            </div>
          </div>
          <div>
            <a href="profile-edit.html" class="btn btn-primary btn-sm d-none d-md-block">Account
              Setting</a>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--main profile end-->
<!--recipe start-->
<section class="pb-5 py-md-5" style="background-color: #f1f5f9;">
  <div class="container">

    {% for myrep in myrecipes %}
      <a href="{% url 'editrecipe' myrep.id %}">
    
        <div class="row">
          <div class="col-lg-3 col-md-6 col-12">
            <!-- Card -->
            <div class="card  mb-4 card-hover">
              <a href="{% url 'editrecipe' myrep.id %}" class="card-img-top"><img src="{{myrep.recipe_image.url}}" alt=""
                  class="card-img-top rounded-top-md"></a>
              <!-- Card body -->
              <div class="card-body">
                <h3 class="h4 mb-2 text-truncate-line-2 "><a href="#" class="text-inherit">
                    {{myrep.recipe_name}}</a>
                </h3>
                <!-- List inline -->
                <ul class="mb-3  list-inline">
                  <li class="list-inline-item"><i class="fa-regular fa-clock  me-1"></i>{{myrep.prep_time}}min
                  </li>
                  <li class="list-inline-item">
                    <i class="fa-solid fa-burger me-1"></i>{{myrep.category}}</li>
                </ul>
                <div class="lh-1">
                  <span>
                    <i class="fa-regular fa-star text-warning me-n1"></i>
                    <i class="fa-regular fa-star text-warning me-n1"></i>
                    <i class="fa-regular fa-star text-warning me-n1"></i>
                    <i class="fa-regular fa-star text-warning me-n1"></i>
                    <i class="fa-regular fa-star text-warning"></i>
                    
                  </span>
                 
                </div>
                <li class="list-inline-item m-2">
                  {{myrep.Main_ingredient}}</li>
              </div>
              <!-- Card footer -->
              <div class="card-footer">
                <div class="row align-items-center g-0">
                 <div class="btn btn-primary">Edit Recipe</div>
                </div>
              </div>
            </div>
          </div>
      </a>
    {% endfor %}
  </div>

</section>
<!--recipe end-->
    

    
    

    
{% endblock main %}
    

product/templates/product/addrecipe.html
{% extends 'product/main.html' %}

{% block main %}
<section class="py-4">
    <div class="container">
        <div class="row pb-4">
            <div class="col-12">
                <!-- Title -->
                <h1 class="mb-0 h2">Create a post</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <!-- Chart START -->
                <div class="card border">
                    <!-- Card body -->
                    <div class="card-body">
                        <!-- Form START -->
                        <form enctype="multipart/form-data" method="post">
                            {% csrf_token %}
                            <!-- Main form -->
                            <div class="row">
                                <div class="col-lg-6">
                                    <!-- Post name -->
                                    <div class="mb-3">
                                        <label class="form-label">Recipe name</label>
                                        <input
                                            required
                                            id="recipe_name"
                                            name="recipe_name"
                                            type="text"
                                            class="form-control"
                                            placeholder="Enter Recipe name.."
                                        >
                                        <small></small>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <!-- Post name -->
                                    <div class="mb-3">
                                        <label class="form-label">Recipe image</label>
                                        <input
                                            class="form-control"
                                            type="file"
                                            name="recipe_image"
                                            id="recipe_image"
                                            accept="image/gif, image/jpeg, image/png"
                                        >
                                        <small>Moving heaven divide two sea female great midst spirit</small>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <!-- Post name -->
                                    <div class="mb-3">
                                        <label class="form-label">Preparation Time</label>
                                        <input
                                            class="form-control"
                                            type="number"
                                            name="prep_time"
                                            id="prep_time"
                                        >
                                        <small>Moving heaven divide two sea female great midst spirit</small>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <!-- Post name -->
                                    <div class="mb-3">
                                        <label class="form-label">Total Time</label>
                                        <input
                                            class="form-control"
                                            type="number"
                                            name="Total_Time"
                                            id="Total_Time"
                                        >
                                        <small>Moving heaven divide two sea female great midst spirit</small>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <!-- Post name -->
                                    <div class="mb-3">
                                        <label class="form-label">Servings</label>
                                        <input
                                            class="form-control"
                                            type="number"
                                            name="Servings"
                                            id="Servings"
                                        >
                                        <small>Moving heaven divide two sea female great midst spirit</small>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <!-- Post name -->
                                    <div class="mb3">
                                        <label class="form-label">Category</label>
                                        <select name="category" id="id_category" class="form-control">
                                            <option value="1">Non_veg</option>
                                            <option value="2">veg</option>
                                        </select>
                                    </div>
                                </div>
                                <!-- Short description -->
                                <div class="col-12">
                                    <div class="mb-3">
                                        <label class="form-label">Short description</label>
                                        <textarea
                                            class="form-control"
                                            rows="3"
                                            placeholder="Add description"
                                            name="small_description"
                                            id="small_description"
                                        ></textarea>
                                    </div>
                                </div>
                                <!--Short description end-->
                                <!--Description-->
                                <div class="col-12">
                                    <div class="mb-3">
                                        <label class="form-label">Description</label>
                                        <textarea
                                            class="form-control"
                                            rows="3"
                                            placeholder="Add description"
                                            name="description"
                                            id="description"
                                        ></textarea>
                                    </div>
                                </div>
                                <!--description end-->
                                <!-- Main toolbar -->
                                <label for="directions mb-3">Directions</label>
                                <div class="col-md-12">
                                    <!-- Subject -->
                                    {{form.media}}
                                     {{form.Directions}}
                                </div>
                                <div class="mb3 mt-3">
                                    <label for="Ingredients">Ingredients</label>
                                </div>
                                <div class="col-md-12">
                                    <!-- Subject -->
                                    {{form.media}}
                                   {{form.Ingredients}}
                                </div>
                                <div class="col-12">
                                    <div class="mb-3"></div>
                                </div>
                                <div class="col-lg-12">
                                    <!-- Message -->
                                    <div class="mb-3">
                                        <label class="form-label">Main_ingredient</label>
                                        <textarea
                                            class="form-control"
                                            rows="3"
                                            placeholder="Main_ingredient"
                                            name="Main_ingredient"
                                            id="Main_ingredient"
                                        ></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <!-- Message -->
                                    <div class="mb-3">
                                        <label class="form-label">Cook_note</label>
                                        <textarea
                                            class="form-control"
                                            rows="3"
                                            placeholder="Main_ingredient"
                                            name="Cook_note"
                                            id="Cook_note"
                                        ></textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-check mb-3">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="postCheck"
                                        >
                                        <label class="form-check-label" for="postCheck">
                                            Make this post featured?
                                        </label>
                                    </div>
                                </div>
                                <!-- Create post button -->
                                <div class="col-md-12 text-start">
                                    <button class="btn btn-primary w-100" type="submit">Create post</button>
                                </div>
                            </div>
                            <input type="hidden" name="user" id="elder" value="">
                        </form>
                        <!-- Form END -->
                    </div>
                </div>
                <!-- Chart END -->
            </div>
        </div>
    </div>
</section>
<script>
      var name = '{{user.id}}';
  document.getElementById('elder').value = name;
</script>
{% endblock main %}

product/templates/product/navbar.html
{% load static %}
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link "  href="{% url 'home' %}">Home</a>
          <a class="nav-link" href="{% url 'register' %}">register</a>
          <a class="nav-link" href="{% url 'login' %}">login</a>
          <a class="nav-link" href="{% url 'account' %}">account</a>
          <a class="nav-link" href="{% url 'logout' %}">logout</a>
          <a class="nav-link" href="{% url 'addrecipe' %}">add recipe</a>


        </div>
      </div>
    </div>
  </nav> -->
<!--navbar-->